/* eslint-disable */
/**
 * Generated Convex API — this file is auto-generated by `npx convex dev`.
 * Do not edit manually. Run `npx convex dev` to regenerate.
 */
import { anyApi } from 'convex/server';
export const api: any = anyApi;
export const internal: any = anyApi;
